
# ----------------------
# Basic colors
# ----------------------
foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #b4befe

# ----------------------
# Cursor
# ----------------------
cursor #cdd6f4
cursor_text_color #1e1e2e

# ----------------------
# URL
# ----------------------
url_color #89b4fa

# ----------------------
# Window borders
# ----------------------
active_border_color #b4befe
inactive_border_color #6c7086
bell_border_color #f9e2af

# ----------------------
# Tab bar
# ----------------------
active_tab_foreground #1e1e2e
active_tab_background #b4befe
inactive_tab_foreground #a6adc8
inactive_tab_background #181825
tab_bar_background #1e1e2e

# ----------------------
# ANSI colors
# ----------------------

# black
color0  #181825
color8  #45475a

# red
color1  #f38ba8
color9  #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #b4befe
color12 #b4befe

# magenta (soft, controlled)
color5  #cba6f7
color13 #cba6f7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #a6adc8
color15 #cdd6f4
